<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>

        <!-- Application - General -->
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Restmium.$(MSBuildProjectName)</AssemblyName>
        <RootNamespace>Restmium.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>

        <!-- Application - Dependencies -->
        <NuGetAudit>True</NuGetAudit>
        <NuGetAuditMode>all</NuGetAuditMode>

        <!-- Global Usings - General -->
        <ImplicitUsings>enable</ImplicitUsings>

        <!-- Build - General -->
        <Nullable>enable</Nullable>

        <!-- Build - Errors and warnings -->
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>

        <!-- Build - Errors and warnings -->
        <NoWarn>CA1515,IDE0005</NoWarn>

        <!-- Build - Output -->
        <GenerateDocumentationFile>False</GenerateDocumentationFile>

        <!-- Code Analysis - All analyzers -->
        <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>True</RunAnalyzersDuringLiveAnalysis>

        <!-- Code Analysis - .NET analyzer -->
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>

    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleODataApi.Infrastructure\SampleODataApi.Infrastructure.csproj">
        <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
    <ProjectReference Include="..\SampleODataApi.UseCases\SampleODataApi.UseCases.csproj">
        <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
